class SiteSettings 
  
  NAME = "Sitename"
  FOURSQUARE_CLIENT_ID = 2RIEFGJ11QYCMK1KW2RECDINMBWEL2IMUWYUC4MGGYGQQBDL
  FOURSQUARE_CLIENT_SECRET = 02SA1F4ZLE3SRFJUM0RKLGJRVWS43M1EAG4DYZEFP1SFISU3
  
end